name: sci_tercen_client
description: Tercen Dart client library.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  sci_tercen_model:
    git:
      url: https://github.com/tercen/sci_tercen_model
      ref: 1.0.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
